Fix flake8 (#7)
* [fix] AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder', which is caused by the version update of flake8

* Fix num digit (#6)

* [test] ELLIPSIS to ignore new fields

* [test] ELLIPSIS to ignore small digits

* [test] ELLIPSIS to ignore small digits

* [test] ELLIPSIS to ignore small digits

* [test] ELLIPSIS to ignore small digits

* [test] ELLIPSIS to ignore small digits